POST http://localhost:8080/kubernetes/counter/increment
Content-Type: application/json

{
  "kind": "deployment",
  "metadataName": "inginx"
}

###
GET http://localhost:8080/kubernetes/counter?kind="DEPLOYMENT"&metadataName="inginx"
Accept: application/json

###
