POST http://localhost:8082/kubernetes/counter/increment
Content-Type: application/json

{
  "kind": "deployment",
  "metadataName": "counter-service",
  "incrementCountBy": 5
}

###
GET http://localhost:8082/kubernetes/counter?kind="DEPLOYMENT"&metadataName="inginx"
Accept: application/json

###
